import type { Metadata } from "next";
import "./globals.css";
import { ToastContainer } from "react-toastify";

import { Jost } from "next/font/google";
const jost = Jost({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cipher Note",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${jost.className}`}>
        {children}
        <ToastContainer
          position="bottom-right"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="dark"
          className={`${jost.className}`}
        />
      </body>
    </html>
  );
}
